version: 2
jobs:
  build:
    docker:
      - image: node:6.11.2-alpine

    working_directory: ~/middy

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: 
          name: update npm
          command: npm install -g npm@5.3.0
      
      - run:
          name: install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - run:
          name: unit tests
          command: npm test